name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "amd64,arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prep Tags
        id: prep
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          TAGS="ghcr.io/bmoers/sn/atf-headless-runner:latest"
          TAGS="$TAGS,ghcr.io/bmoers/sn/atf-headless-runner:sha-${GITHUB_SHA::8}"
          TAGS="$TAGS,ghcr.io/bmoers/sn/atf-headless-runner:${VERSION}"
          echo ::set-output name=tags::${TAGS}
          

      - name: Build Docker images & push to Github Packages
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          platforms: linux/amd64,linux/arm64
          pull: false
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=Alternative Headless ATF Runner for ServiceNow

